### ISSUE TITLE
[Android] Unsupprted Flag 256 for Pattern.java

### ISSUE THREAD

**Issue by EssidM** [mapcode-foundation/mapcode-java-example#6]

**Comment by EssidM** [comment]
I'm trying to decode map in a Android Application using this code snippet 

 point = MapcodeCodec.decode(item.getClientMapCode(), Territory.TUN);

but I am getting this exception 

java.lang.ExceptionInInitializerError
            at com.mapcode.MapcodeCodec.decode(MapcodeCodec.java:217)

 Caused by: java.lang.IllegalArgumentException: Unsupported flags: 256
            at java.util.regex.Pattern.<init>(Pattern.java:390)
            at java.util.regex.Pattern.compile(Pattern.java:374)
            at com.mapcode.Mapcode.<clinit>(Mapcode.java:265)
            at com.mapcode.MapcodeCodec.decode(MapcodeCodec.java:217)

I think that the problem is caused by the Pattern.java in android framework which is belongs to Java 1.6 and for MapCode it uses the 1.7.

How can I solve this Problem ? there is an API for Android ( can't find it :( !!)

**Comment by rijnb** [comment]
You are correct in assuming this is caused by Java 6 vs. Java 7. We are using `Pattern.compile(..., Pattern.UNICODE_CHARACTER_CLASS)` which is not supported in Java 6.
I've created a fix for the Java library and the example in the `dev` branch, which moves the library back to JDK 1.6. Could you have a try and see if the compiled version of the `dev` branch (and using that self-compiled JAR in your project) actually works on Android? (Let me know if there is a problem in trying that.)

You can find the dev branch for the Mapcode Java library here:
https://github.com/mapcode-foundation/mapcode-java/tree/dev

The `pom.xml` version is 2.0.1-SNAPSHOT for that branch. The `mapcode-java-example` has been updated as well in the `dev` branch.

**Comment by EssidM** [comment]
Dear Rijin,

Thank for your quick reply.

Unfortunatly, I couldn't be able to test MapCode , it seems that there is a
problem with "DataAccess": I think that this is java version and  should be
adapted to data access on Android so the app will be able to retrieve
"mminfo.dat".

Regards.

2015-07-08 13:09 GMT+01:00 Rijn Buve notifications@github.com:

> You are correct in assuming this is caused by Java 6 vs. Java 7. We are
> using Pattern.compile(..., Pattern.UNICODE_CHARACTER_CLASS) which is not
> supported in Java 6.
> I've created a fix for the Java library and the example in the 'dev'
> branch, which moves the library back to JDK 1.6. Could you have a try and
> see if the compiled version of the 'dev' branch (and using that
> self-compiled JAR in your project) actually works on Android?
> You can find the dev branch for the Mapcode Java library here:
> https://github.com/mapcode-foundation/mapcode-java/tree/dev
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mapcode-foundation/mapcode-java-example/issues/6#issuecomment-119553181
> .

## 

Essid Mohamed

Ingénieur de Conception & Développement

_Tel_: +216 22 919 312

**Comment by rijnb** [comment]
OK. I have just released version 2.0.1 of the Java library, which has now been fully reverted to JDK 1.6/Java 6 to accommodate Android. It does not address the accessibility of mminfo.dat, however.

Perhaps I can also point you at our online service? Just enter http://api.mapcode.com/mapcode in your browser to get the full REST API docs.

If you would like to submit a solution for the data access, please feel free to contact me.
